In [17]:
import numpy as np
import pandas as pd
from numpy.linalg import inv
import math

In [18]:
#Load classificationA.train
classificationA_train = np.array(pd.read_csv("classificationA.train", header=None, sep  = "\t"))
classificationA_train_Y = np.copy(classificationA_train[:,2])
classificationA_train_Y = classificationA_train_Y.reshape(classificationA_train_Y.shape[0],1)
classificationA_train_X = np.copy(classificationA_train)
classificationA_train_X[:,2] = 1

#Load classificationB.train
classificationB_train = np.array(pd.read_csv("classificationB.train", header=None, sep  = "\t"))
classificationB_train_Y = np.copy(classificationB_train[:,2])
classificationB_train_Y = classificationB_train_Y.reshape(classificationB_train_Y.shape[0],1)
classificationB_train_X = np.copy(classificationB_train)
classificationB_train_X[:,2] = 1
    
#Load classificationC.train
classificationC_train = np.array(pd.read_csv("classificationC.train", header=None, sep  = "\t"))
classificationC_train_Y = np.copy(classificationC_train[:,2])
classificationC_train_Y = classificationC_train_Y.reshape(classificationC_train_Y.shape[0],1)
classificationC_train_X = np.copy(classificationC_train)
classificationC_train_X[:,2] = 1

In [19]:
classificationA_train_X

array([[-3.60340505,  1.3266    ,  1.        ],
       [-4.2190114 ,  2.015     ,  1.        ],
       [-1.51565812,  0.5059    ,  1.        ],
       [-1.16975695,  0.3815    ,  1.        ],
       [ 0.52274116, -0.6572    ,  1.        ],
       [-0.14174035, -0.7083    ,  1.        ],
       [-3.2644966 ,  1.312     ,  1.        ],
       [-1.7093627 ,  0.2236    ,  1.        ],
       [-2.06451872,  0.6392    ,  1.        ],
       [-2.7745778 ,  1.139     ,  1.        ],
       [-4.4637327 ,  1.2861    ,  1.        ],
       [-2.05557939,  0.716     ,  1.        ],
       [-4.93081485,  1.9442    ,  1.        ],
       [-2.78573378,  0.8165    ,  1.        ],
       [-3.78492412,  1.0945    ,  1.        ],
       [-0.023503  , -0.1801    ,  1.        ],
       [-4.0787268 ,  1.6789    ,  1.        ],
       [-4.88879174,  2.2006    ,  1.        ],
       [-4.11260798,  1.3405    ,  1.        ],
       [-5.11303227,  1.578     ,  1.        ],
       [-2.76271871,  0.6868    ,  1.   

In [20]:
classificationA_train_Y

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
      

In [21]:
def linear_regression(X,y):
    return inv(X.transpose().dot(X)).dot(X.transpose()).dot(y)

In [22]:
linear_regression(classificationA_train_X,classificationA_train_Y)

array([[-0.2640075 ],
       [-0.37259311],
       [ 0.49229204]])

In [23]:
linear_regression(classificationB_train_X,classificationB_train_Y)

array([[-0.10424575],
       [ 0.05179118],
       [ 0.50005043]])

In [24]:
linear_regression(classificationC_train_X,classificationC_train_Y)

array([[-0.12769333],
       [-0.01700142],
       [ 0.50839982]])