In [1]:
import numpy as np
import pandas as pd
from numpy.linalg import inv
import math

In [2]:
#Load classificationA.train
classificationA_train = np.array(pd.read_csv("classificationA.train", header=None, sep  = "\t"))
classificationA_train_Y = np.copy(classificationA_train[:,2])
classificationA_train_Y = classificationA_train_Y.reshape(classificationA_train_Y.shape[0],1)
classificationA_train_X = np.copy(classificationA_train)
classificationA_train_X[:][2] = 1

#Load classificationB.train
classificationB_train = np.array(pd.read_csv("classificationB.train", header=None, sep  = "\t"))
classificationB_train_Y = np.copy(classificationB_train[:,2])
classificationB_train_Y = classificationB_train_Y.reshape(classificationB_train_Y.shape[0],1)
classificationB_train_X = np.copy(classificationB_train)
classificationB_train_X[:][2] = 1
    
#Load classificationC.train
classificationC_train = np.array(pd.read_csv("classificationC.train", header=None, sep  = "\t"))
classificationC_train_Y = np.copy(classificationC_train[:,2])
classificationC_train_Y = classificationC_train_Y.reshape(classificationC_train_Y.shape[0],1)
classificationC_train_X = np.copy(classificationC_train)
classificationC_train_X[:][2] = 1

In [3]:
def linear_regression(X,y):
    return inv(X.transpose().dot(X)).dot(X.transpose()).dot(y)

In [5]:
linear_regression(classificationA_train_X,classificationA_train_Y)

array([[  1.22298005e-16],
       [  3.60822483e-16],
       [  1.00000000e+00]])

In [6]:
linear_regression(classificationB_train_X,classificationB_train_Y)

array([[ -4.33680869e-19],
       [ -1.04083409e-17],
       [  1.00000000e+00]])

In [7]:
linear_regression(classificationC_train_X,classificationC_train_Y)

array([[  3.46944695e-18],
       [  3.72965547e-17],
       [  1.00000000e+00]])