In [1]:
import numpy as np
import pandas as pd
from numpy.linalg import inv
import math

In [2]:
def sigmoid(z):
    return math.exp(z)/(1+math.exp(z))

def nu(vector):
    return 1/(1+np.exp(-vector))

def diag_nu(vector):
    temp = nu(vector)*(1-nu(vector))
    return np.diag(temp[:,0])

def logistic_regression(X, y, max_iter):
    print(y.shape)
    w = np.zeros([3,1])
    print(w)
    for i in range(max_iter):
        d_nu = diag_nu(X.dot(w))
        v_nu = nu(X.dot(w))
        temp = inv(X.transpose().dot(d_nu).dot(X))
        temp1 = temp.dot(X.transpose())
        y_nu = y-v_nu
        w_ = temp1.dot(y_nu)
        #w_ = inv(X.transpose().dot(d_nu).dot(X)).dot(X.transpose()).dot(y-v_nu)
        w_ = w_.reshape(3,1)
        w = w + w_
        print(w)

In [3]:
#Load classificationA.train
classificationA_train = np.array(pd.read_csv("classificationA.train", header=None, sep  = "\t"))
classificationA_train_Y = np.copy(classificationA_train[:,2])
classificationA_train_Y = classificationA_train_Y.reshape(classificationA_train_Y.shape[0],1)
classificationA_train_X = np.copy(classificationA_train)
classificationA_train_X[:][2] = 1

#Load classificationB.train
classificationB_train = np.array(pd.read_csv("classificationB.train", header=None, sep  = "\t"))
classificationB_train_Y = np.copy(classificationB_train[:,2])
classificationB_train_Y = classificationB_train_Y.reshape(classificationB_train_Y.shape[0],1)
classificationB_train_X = np.copy(classificationB_train)
classificationB_train_X[:][2] = 1
    
#Load classificationC.train
classificationC_train = np.array(pd.read_csv("classificationC.train", header=None, sep  = "\t"))
classificationC_train_Y = np.copy(classificationC_train[:,2])
classificationC_train_Y = classificationC_train_Y.reshape(classificationC_train_Y.shape[0],1)
classificationC_train_X = np.copy(classificationC_train)
classificationC_train_X[:][2] = 1

In [4]:
logistic_regression(classificationC_train_X,classificationC_train_Y,50)

(400, 1)
[[ 0.]
 [ 0.]
 [ 0.]]
[[-0.35758321]
 [ 0.02047747]
 [ 0.98073948]]
[[-0.61922879]
 [ 0.15507456]
 [ 1.76758279]]
[[-0.89508726]
 [ 0.37630964]
 [ 2.82574484]]
[[-1.20411269]
 [ 0.67129221]
 [ 4.17180748]]
[[-1.55175444]
 [ 1.01199562]
 [ 5.7184619 ]]
[[-1.91912446]
 [ 1.35141952]
 [ 7.33844522]]
[[-2.24153311]
 [ 1.61893224]
 [ 8.89722975]]
[[ -2.42839312]
 [  1.75008943]
 [ 10.2399407 ]]
[[ -2.47771845]
 [  1.77535422]
 [ 11.33735646]]
[[ -2.48165174]
 [  1.77621607]
 [ 12.3490434 ]]
[[ -2.48176764]
 [  1.7762129 ]
 [ 13.35141131]]
[[ -2.48177343]
 [  1.77621288]
 [ 14.3522385 ]]
[[ -2.48177411]
 [  1.77621288]
 [ 15.35254098]]
[[ -2.4817742 ]
 [  1.77621288]
 [ 16.35265205]]
[[ -2.48177422]
 [  1.77621288]
 [ 17.35269288]]
[[ -2.48177422]
 [  1.77621288]
 [ 18.3527079 ]]
[[ -2.48177422]
 [  1.77621288]
 [ 19.35271342]]
[[ -2.48177422]
 [  1.77621288]
 [ 20.35271545]]
[[ -2.48177422]
 [  1.77621288]
 [ 21.3527162 ]]
[[ -2.48177422]
 [  1.77621288]
 [ 22.35271648]]
[[ -2.4817

LinAlgError: Singular matrix

In [ ]:
classificationA_train_Y.shape[1]